### PR TITLE
Bump CI to 9.2.5 and 9.4.3

### PR DESCRIPTION
**Pull request by andreasabel**
Bump CI to 9.2.5 and 9.4.3

### CODE REVIEW

**Comment by ddssff** [comment]
Are these cancelled checks a concern?

**Comment by andreasabel** [comment]
Experience tells me to worry... yes.

**Comment by andreasabel** [comment]
> Are these cancelled checks a concern?

Didn't seem to worry you enough to pause the release...

Anyway, [this is where](https://github.com/ddssff/listlike/actions/runs/3469471030/jobs/5798300085#step:20:7208) the 9.4.3 CI freezes:
```
Testing 2:ListLike:60:sort:14:DList Int                                     

+++ OK, passed 100 tests.
Cases: 2274  Tried: 1794  Errors: 0  Failures: 0
Error: The operation was canceled.
```
[Same](https://github.com/ddssff/listlike/actions/runs/3469471030/jobs/5798300299#step:20:7208) for the 9.2.5 CI.

On my machine (macOS) with GHC 9.4.3 this runs though:
```
...
Testing 2:ListLike:60:sort:14:DList Int                                     
Cases: 2274  Tried: 1794  Errors: 0  Failures: 0+++ OK, passed 100 tests.
Testing 2:ListLike:60:sort:15:Vector Int                                    
Cases: 2274  Tried: 1795  Errors: 0  Failures: 0+++ OK, passed 100 tests.
...
```
This could mean that a `Vector` test fails.  But I see no reason why it fails.

@ddssff Do you have access to Linux or Windows machines to test there?

**Comment by andreasabel** [comment]
Actually now the tests pass.  
Not sure how to interpret this.  Since these are random test, of course they could hit a bad corner once in a while...

**Pull request merged**
