### PR TITLE
Test compilation 7.10 -- 8.10 with GitHub Actions

### LINKED ISSUE #6: Build failures with GHC 7.6 and 7.8
With 7.6:

```
src/Data/ListLike/Base.hs:54:18:
    Module `GHC.Exts' does not export `IsList(Item, fromList, toList)'
```

With 7.8:

```
src/Data/ListLike/Instances.hs:544:16:
    Couldn't match type ‘Item (S.Seq Char)’ with ‘Char’
    Expected type: S.Seq Char -> String
      Actual type: S.Seq Char -> [Item (S.Seq Char)]
    In the expression: toList
    In an equation for ‘toString’: toString = toList

src/Data/ListLike/Instances.hs:555:10:
    Couldn't match type ‘a’ with ‘Item (S.Seq a)’
      ‘a’ is a rigid type variable bound by
          the instance declaration at src/Data/ListLike/Instances.hs:555:10
    In the instance declaration for ‘ListLike (S.Seq a) a’

src/Data/ListLike/Instances.hs:567:24:
    Could not deduce (item' ~ Item (S.Seq item'))
    from the context (IsList (S.Seq a),
                      a ~ Item (S.Seq a),
                      FoldableLL (S.Seq a) a,
                      Monoid (S.Seq a))
      bound by the instance declaration
      at src/Data/ListLike/Instances.hs:555:10-29
    or from (ListLike full' item')
      bound by the type signature for
                 map :: ListLike full' item' => (a -> item') -> S.Seq a -> full'
      at src/Data/ListLike/Instances.hs:567:5-7
      ‘item'’ is a rigid type variable bound by
              the type signature for
                map :: ListLike full' item' => (a -> item') -> S.Seq a -> full'
              at src/Data/ListLike/Instances.hs:567:5
    Expected type: S.Seq item' -> [item']
      Actual type: S.Seq item' -> [Item (S.Seq item')]
    Relevant bindings include
      f :: a -> item' (bound at src/Data/ListLike/Instances.hs:567:9)
      map :: (a -> item') -> S.Seq a -> full'
        (bound at src/Data/ListLike/Instances.hs:567:5)
    In the first argument of ‘(.)’, namely ‘toList’
    In the second argument of ‘(.)’, namely ‘toList . fmap f’

src/Data/ListLike/Instances.hs:587:24:
    Could not deduce (Item (S.Seq (S.Seq a)) ~ S.Seq a)
    from the context (IsList (S.Seq a),
                      a ~ Item (S.Seq a),
                      FoldableLL (S.Seq a) a,
                      Monoid (S.Seq a))
      bound by the instance declaration
      at src/Data/ListLike/Instances.hs:555:10-29
    or from (ListLike full' (S.Seq a))
      bound by the type signature for
                 inits :: ListLike full' (S.Seq a) => S.Seq a -> full'
      at src/Data/ListLike/Instances.hs:587:5-9
    Expected type: S.Seq (S.Seq a) -> [S.Seq a]
      Actual type: S.Seq (S.Seq a) -> [Item (S.Seq (S.Seq a))]
    Relevant bindings include
      inits :: S.Seq a -> full'
        (bound at src/Data/ListLike/Instances.hs:587:5)
    In the first argument of ‘(.)’, namely ‘toList’
    In the second argument of ‘(.)’, namely ‘toList . S.inits’

src/Data/ListLike/Instances.hs:588:24:
    Could not deduce (Item (S.Seq (S.Seq a)) ~ S.Seq a)
    from the context (IsList (S.Seq a),
                      a ~ Item (S.Seq a),
                      FoldableLL (S.Seq a) a,
                      Monoid (S.Seq a))
      bound by the instance declaration
      at src/Data/ListLike/Instances.hs:555:10-29
    or from (ListLike full' (S.Seq a))
      bound by the type signature for
                 tails :: ListLike full' (S.Seq a) => S.Seq a -> full'
      at src/Data/ListLike/Instances.hs:588:5-9
    Expected type: S.Seq (S.Seq a) -> [S.Seq a]
      Actual type: S.Seq (S.Seq a) -> [Item (S.Seq (S.Seq a))]
    Relevant bindings include
      tails :: S.Seq a -> full'
        (bound at src/Data/ListLike/Instances.hs:588:5)
    In the first argument of ‘(.)’, namely ‘toList’
    In the second argument of ‘(.)’, namely ‘toList . S.tails’
```

My suggestion would be to simply bump the lower bound on `base`. Since this issue [has existed](https://matrix.hackage.haskell.org/#/package/ListLike) since the release of 4.7 in April, I assume there's not much demand for compatibility with GHC < 7.10.

### PR DESCRIPTION
**Pull request by andreasabel**
Test compilation 7.10 -- 8.10 with GitHub Actions

* bump to 4.7.3
* require base >= 4.8 (fixes #6)
* `haskell-ci` generated tests on GitHub Actions

### CODE REVIEW

**Comment by andreasabel** [comment]
@ddssff : I think you need to activate Actions.
See successful action run on my account at: https://github.com/andreasabel/listlike/actions/runs/449372388

**Review by sjakobi — COMMENTED** [review]
LGTM!

**Comment by ddssff** [comment]
Thanks for the patches!

**Comment by ddssff** [comment]
can someone explain like I'm drunk if there's something else I need to do?

**Comment by andreasabel** [comment]
The actions ran fine.

I suppose all is left is to release on hackage.

**Pull request merged**
